# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|

    if options[:message]
      changelog = options[:message]
    else
      changelog = prompt(text: "Changelog: ", multi_line_end_keyword: "END")
    end

    get_certificates
    get_provisioning_profile

    if options[:build]
      build = options[:build]
    else
      build = latest_testflight_build_number + 1
    end

    increment_build_number({ build_number: build })

    build_app(scheme: "spacedRepetition")
    notification(subtitle: "Spaced Repetition", message: "Build complete")

    upload_to_testflight(changelog: changelog)
    notification(subtitle: "Spaced Repetition", message: "Build uploaded")
  end
end
